Feat 게시물생성
f-lab-edu/cat-caring-community pull request #10
Opened 2021-05-18 06:43 UTC by parks38

- 게시물 post save

2021-05-22 17:16 UTC, f-lab-hubert requested changes
https://github.com/f-lab-edu/cat-caring-community/pull/6 요 PR과 겹치는 코드가 있어서 해당부분은 별도로 다시 리뷰드리진 않았습니다 :) Post관련 부분만 리뷰드렸어요 ㅎ

2021-05-22 17:16 UTC, f-lab-hubert commented on src/main/java/com/project/catcaring/mapper/PostMapper.java
> +  void insertTag(Tag postTag);
PostMapper에 Post가 아닌 도메인 객체에 대해서도 insert 인터페이스가 있는데 이유가 있으실까요?? 단일책임원칙을 고려해보면 별도의 인터페이스로 분리되는거 어떨까 싶어서요 ㅎ

2021-05-22 17:16 UTC, f-lab-hubert commented on src/main/java/com/project/catcaring/service/PostServiceImpl.java
> +  }
Post나 Location의 생성 로직은 Service가 가져가기 보다는 각각의 객체에서 책임을 갖는 것은 어떨까요??
예를 들면
```java
public class Post {
    ...
    public static Post create(PostInfoRequest postInfoRequest, Long userId) {
        Authority authority = postInfoRequest.getPostAuthorityCode();
        if(authority == null) {
            authority = Authority.ALL;
        }
        return Post.builder().userId(userId).title(postInfoRequest.getTitle())..content(postInfoRequest.getContent()).authorityCode(authority).status(PostStatus.CREATED).build();
    }
    ...
}
```
위와 같이 생성로직이 Post 클래스에 있다면 PostServiceImpl에는 Post.create(postInfoRequest, postId)를 사용해서 Post 객체를 생성할 수 있습니다. PostServiceImpl는 Post관련 비즈니스 로직이 있는 곳이고 생성관련 로직은 Post가 가져가는게 좋을 것 같아서요 :) Location 객체생성 부분도 같은 의견입니다 :)

2021-06-07 17:19 UTC, f-lab-hubert commented on src/main/java/com/project/catcaring/dto/user/response/UserInfoResponse.java
> +public class UserInfoResponse {
요정도의 dto라면 User를 직접 내리는 게 좋지 않을까요???

2021-06-08 12:36 UTC, parks38 commented
게시물 수정에 모두 merge

2021-06-08 12:36 UTC, closed without merging