Feat 게시물삭제
f-lab-edu/cat-caring-community pull request #11
Opened 2021-05-18 12:49 UTC by parks38

- 게시물 삭제 비즈니스 로직
    - controller
    - serviceImpl
    - mapper
    - mapper.xml 
    - handler

2021-05-22 23:52 UTC, f-lab-hubert requested changes
다른 branch에 이미 리뷰를 드렸던 부분들은 다시 리뷰드리지 않고 새로운 코드 부분에만 리뷰를 드렸습니다 :)

2021-05-22 23:52 UTC, f-lab-hubert commented on src/main/java/com/project/catcaring/controller/PostController.java
> +    log.info(username + "님 (userId: " + userId + ") 의 포스트 업로드를 시작합니다. ");
로그를 찍을 때 String + 로 연결하기 보다는 주로 formatting형식을 사용해요 :)
예를 들면
```java
log.info("{} 님 (userId: {}) 의 포스트 업로드를 시작합니다.", username, userId);
```
요렇게요 :)

2021-05-22 23:52 UTC, f-lab-hubert commented on src/main/java/com/project/catcaring/controller/PostController.java
> +  private final PostServiceImpl postService;
인터페이스를 만들어주신것 같은데 구현체를 직접 의존한 이유가 있으실까요??

2021-05-22 23:52 UTC, f-lab-hubert commented on src/main/java/com/project/catcaring/controller/PostController.java
> +    String username = loginSessionService.getCurrentUsername(session);
User정보가 필요해서 UserService를 이용하여 정보를 갖고오는 로직이 중복으로 많이 등장하는 것 같은데요. 해당 관심사를 HandlerMethodArgumentResolver를 이용하여 분리할 수도 있을 것 같아요 :)
https://velog.io/@kingcjy/Spring-HandlerMethodArgumentResolver%EC%9D%98-%EC%82%AC%EC%9A%A9%EB%B2%95%EA%B3%BC-%EB%8F%99%EC%9E%91%EC%9B%90%EB%A6%AC
해당 링크 한번 확인해보시고 적용해봐도 좋을 것 같습니다. AOP를 이용하셔도 좋구요 :)

2021-05-22 23:52 UTC, f-lab-hubert commented on src/main/java/com/project/catcaring/controller/UserController.java
> +  @RequestMapping(path = {"/signup"}, method = {RequestMethod.POST})
요건 사소한 부분인데요 ㅎ signup을 path로 사용하셨으면 로그인도 signin으로 맞춰주는건 어떨까요?? ㅎㅎ

2021-05-22 23:52 UTC, f-lab-hubert commented on src/main/java/com/project/catcaring/domain/Post.java
> +  @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
@JsonFormat을 이용하여 time타입에 대한 json format을 맞춰 줄 수도 있지만 보통 API Spec에서 time format은 글로벌하게 설정해두고 사용하더라구요. 저도 그런 편이구요. ObjectMapper에 timemodule을 등록해서 사용하면 global하게 설정이 됩니다.
https://jeong-pro.tistory.com/202 요것을 참고하거나 spring jackson objectmapper time format과 같이 구글링해서 살펴보셔도 좋을 것 같아요:)

2021-05-22 23:52 UTC, f-lab-hubert commented on src/main/java/com/project/catcaring/service/PostServiceImpl.java
> +      throw new InvalidProcessException("해당 포스트가 존재하지 않습니다.");
NotFoundEntity 같은 Exception을 만들어서 사용하는 건 어떨까요?? Exception type과 문맥이 어울리지 않는 것 같아서요 ㅎㅎ

2021-06-08 12:36 UTC, parks38 commented
게시물 수정에 모두 merge

2021-06-08 12:36 UTC, parks38 commented
게시물 수정에 모두 merge

2021-06-08 12:36 UTC, parks38 commented
게시물 수정에 모두 merge

2021-06-08 12:36 UTC, closed without merging